-- Agregar columnas faltantes a la tabla members
ALTER TABLE members 
  ADD COLUMN IF NOT EXISTS resolution TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS aspect_ratio TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS crosshair TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS acs TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS adr TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS kast TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS fk TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS fd TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS cover TEXT DEFAULT '';
