-- Add missing columns to the members table for extra profile fields
-- Run this in your Supabase SQL editor (https://supabase.com/dashboard/project/PROJECT_REF/sql/new)

ALTER TABLE members ADD COLUMN IF NOT EXISTS hs_percent TEXT DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS kd TEXT DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS dpr TEXT DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS course TEXT DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS riot_id TEXT DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS region TEXT DEFAULT 'latam';
ALTER TABLE members ADD COLUMN IF NOT EXISTS tracker_url TEXT DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS country TEXT DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS cover TEXT DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS discord TEXT DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS youtube TEXT DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS twitter TEXT DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS twitch TEXT DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS dpi TEXT DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS sens TEXT DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS scoped_sens TEXT DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS hz TEXT DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS raw_input TEXT DEFAULT '';
